version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: test 
      INFLUXDB_ADMIN_USER: admin 
      INFLUXDB_ADMIN_PASSWORD: supersecret 
      INFLUXDB_USER: test 
      INFLUXDB_USER_PASSWORD: test  
    
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb

  
  chronograph:
    image: chronograf
    ports:
      - 8888:8888
    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  proxy : 
    build:
     context: .
     dockerfile: Dockerfile
    image : nginx-custom
    
    ports:
      - 80:80
    




